### ISSUE TITLE
Write installation instructions on readme.md file

### ISSUE THREAD

**Issue by alan707** [shapeable/prototype-web#25]

**Comment by alan707** [comment]
@mikesaurio lo que me referia con este issue es escribir las instrucciones en el README.md principal del master branch (no el que esta adentro de la aplicación)

**Comment by alan707** [comment]
Diana, we are missing the installation instructions for docker specifically by @Gidrek

**Comment by dherrera-civica** [comment]
The installation instructions are already in point "s" of the technical approach
